export type DiscoveredResource = {
  type: 'playbook' | 'role' | 'collection-dep' | 'execution-environment';
  count: number;
};

export type DiscoveredRepo = {
  name: string;
  org: string;
  provider: 'github' | 'gitlab';
  url: string;
  branch: string;
  visibility: 'public' | 'private' | 'internal';
  discoveredAt: string;
  lastCommitHash: string;
  lastCommitMessage: string;
  lastCommitAuthor: string;
  lastCommitTimestamp: string;
  resources: DiscoveredResource[];
  hasProject: boolean;
};

export const DISCOVERED_REPOS: DiscoveredRepo[] = [
  {
    name: 'linux-baseline-hardening',
    org: 'acme-corp',
    provider: 'github',
    url: 'https://github.com/acme-corp/linux-baseline-hardening',
    branch: 'main',
    visibility: 'private',
    discoveredAt: '2026-03-20 09:15',
    lastCommitHash: 'b4a2e19',
    lastCommitMessage: 'update CIS Level 1 benchmarks for RHEL 9.4',
    lastCommitAuthor: 'priya.patel',
    lastCommitTimestamp: '2026-03-19 16:42',
    resources: [
      { type: 'playbook', count: 5 },
      { type: 'role', count: 3 },
      { type: 'collection-dep', count: 2 },
    ],
    hasProject: false,
  },
  {
    name: 'vmware-lifecycle-ops',
    org: 'acme-corp',
    provider: 'github',
    url: 'https://github.com/acme-corp/vmware-lifecycle-ops',
    branch: 'main',
    visibility: 'internal',
    discoveredAt: '2026-03-20 09:15',
    lastCommitHash: '8e7f1c3',
    lastCommitMessage: 'add VM snapshot cleanup playbook',
    lastCommitAuthor: 'sarah.chen',
    lastCommitTimestamp: '2026-03-18 11:30',
    resources: [
      { type: 'playbook', count: 8 },
      { type: 'role', count: 2 },
      { type: 'collection-dep', count: 3 },
      { type: 'execution-environment', count: 1 },
    ],
    hasProject: false,
  },
  {
    name: 'database-backup-automation',
    org: 'acme-corp',
    provider: 'gitlab',
    url: 'https://gitlab.acme-corp.com/dba-team/database-backup-automation',
    branch: 'develop',
    visibility: 'private',
    discoveredAt: '2026-03-20 09:16',
    lastCommitHash: 'a12c4f8',
    lastCommitMessage: 'fix: PostgreSQL backup rotation schedule',
    lastCommitAuthor: 'david.lee',
    lastCommitTimestamp: '2026-03-20 08:55',
    resources: [
      { type: 'playbook', count: 4 },
      { type: 'role', count: 1 },
      { type: 'collection-dep', count: 2 },
    ],
    hasProject: false,
  },
  {
    name: 'k8s-cluster-provisioning',
    org: 'platform-team',
    provider: 'github',
    url: 'https://github.com/platform-team/k8s-cluster-provisioning',
    branch: 'main',
    visibility: 'private',
    discoveredAt: '2026-03-20 09:15',
    lastCommitHash: 'f5d9a2b',
    lastCommitMessage: 'upgrade to kubernetes 1.30 manifests',
    lastCommitAuthor: 'alex.kim',
    lastCommitTimestamp: '2026-03-17 14:20',
    resources: [
      { type: 'playbook', count: 6 },
      { type: 'role', count: 4 },
      { type: 'collection-dep', count: 5 },
      { type: 'execution-environment', count: 1 },
    ],
    hasProject: false,
  },
  {
    name: 'windows-server-patching',
    org: 'platform-team',
    provider: 'github',
    url: 'https://github.com/platform-team/windows-server-patching',
    branch: 'main',
    visibility: 'private',
    discoveredAt: '2026-03-20 09:15',
    lastCommitHash: 'c7e3b11',
    lastCommitMessage: 'add pre-patch snapshot for critical servers',
    lastCommitAuthor: 'james.wu',
    lastCommitTimestamp: '2026-03-16 09:10',
    resources: [
      { type: 'playbook', count: 3 },
      { type: 'role', count: 2 },
      { type: 'collection-dep', count: 1 },
    ],
    hasProject: false,
  },
  {
    name: 'load-balancer-configs',
    org: 'acme-corp',
    provider: 'github',
    url: 'https://github.com/acme-corp/load-balancer-configs',
    branch: 'main',
    visibility: 'internal',
    discoveredAt: '2026-03-20 09:16',
    lastCommitHash: '2a8d4e6',
    lastCommitMessage: 'add F5 BIG-IP health monitor templates',
    lastCommitAuthor: 'maria.garcia',
    lastCommitTimestamp: '2026-03-15 13:45',
    resources: [
      { type: 'playbook', count: 4 },
      { type: 'role', count: 1 },
      { type: 'collection-dep', count: 2 },
    ],
    hasProject: false,
  },
  {
    name: 'ansible-ee-custom-builds',
    org: 'acme-corp',
    provider: 'github',
    url: 'https://github.com/acme-corp/ansible-ee-custom-builds',
    branch: 'main',
    visibility: 'private',
    discoveredAt: '2026-03-20 09:16',
    lastCommitHash: '91b5c0d',
    lastCommitMessage: 'add Python 3.12 base image variant',
    lastCommitAuthor: 'sarah.chen',
    lastCommitTimestamp: '2026-03-19 10:00',
    resources: [
      { type: 'execution-environment', count: 4 },
    ],
    hasProject: false,
  },
  {
    name: 'web-app-scaling-suite',
    org: 'acme-corp',
    provider: 'github',
    url: 'https://github.com/acme-corp/web-app-scaling-suite',
    branch: 'main',
    visibility: 'private',
    discoveredAt: '2026-03-10 14:22',
    lastCommitHash: 'lab482683',
    lastCommitMessage: 'fix: adjust scaling thresholds for peak traffic',
    lastCommitAuthor: 'sarah.chen',
    lastCommitTimestamp: '2026-03-14 09:12',
    resources: [
      { type: 'playbook', count: 3 },
      { type: 'role', count: 1 },
      { type: 'collection-dep', count: 1 },
      { type: 'execution-environment', count: 1 },
    ],
    hasProject: true,
  },
  {
    name: 'rhel-patch-automation',
    org: 'acme-corp',
    provider: 'github',
    url: 'https://github.com/acme-corp/rhel-patch-automation',
    branch: 'main',
    visibility: 'private',
    discoveredAt: '2026-03-10 14:22',
    lastCommitHash: 'a1c9d83',
    lastCommitMessage: 'fix: handle RHEL 9.4 kernel dependency',
    lastCommitAuthor: 'david.lee',
    lastCommitTimestamp: '2026-03-13 11:20',
    resources: [
      { type: 'playbook', count: 4 },
      { type: 'role', count: 2 },
      { type: 'collection-dep', count: 1 },
      { type: 'execution-environment', count: 1 },
    ],
    hasProject: true,
  },
  {
    name: 'network-compliance-checker',
    org: 'acme-corp',
    provider: 'github',
    url: 'https://github.com/acme-corp/network-compliance-checker',
    branch: 'main',
    visibility: 'private',
    discoveredAt: '2026-03-10 14:22',
    lastCommitHash: 'f9a21c7',
    lastCommitMessage: 'feat: add Arista EOS compliance rules',
    lastCommitAuthor: 'james.wu',
    lastCommitTimestamp: '2026-03-16 08:45',
    resources: [
      { type: 'playbook', count: 3 },
      { type: 'role', count: 2 },
      { type: 'collection-dep', count: 2 },
      { type: 'execution-environment', count: 1 },
    ],
    hasProject: true,
  },
  {
    name: 'aws-provisioner',
    org: 'acme-corp',
    provider: 'github',
    url: 'https://github.com/acme-corp/aws-provisioner',
    branch: 'main',
    visibility: 'private',
    discoveredAt: '2026-03-10 14:22',
    lastCommitHash: '3e8b1a4',
    lastCommitMessage: 'chore: update instance type defaults to m6i',
    lastCommitAuthor: 'maria.garcia',
    lastCommitTimestamp: '2026-03-15 16:02',
    resources: [
      { type: 'playbook', count: 3 },
      { type: 'collection-dep', count: 2 },
      { type: 'execution-environment', count: 1 },
    ],
    hasProject: true,
  },
  {
    name: 'firewall-policy-engine',
    org: 'acme-corp',
    provider: 'gitlab',
    url: 'https://gitlab.acme-corp.com/security/firewall-policy-engine',
    branch: 'develop',
    visibility: 'private',
    discoveredAt: '2026-03-10 14:23',
    lastCommitHash: '7d4e5f2',
    lastCommitMessage: 'feat: add zone-based policy rules',
    lastCommitAuthor: 'alex.kim',
    lastCommitTimestamp: '2026-03-16 10:30',
    resources: [
      { type: 'playbook', count: 3 },
      { type: 'collection-dep', count: 1 },
      { type: 'execution-environment', count: 1 },
    ],
    hasProject: true,
  },
  {
    name: 'cis-compliance-scanner',
    org: 'acme-corp',
    provider: 'github',
    url: 'https://github.com/acme-corp/cis-compliance-scanner',
    branch: 'main',
    visibility: 'private',
    discoveredAt: '2026-03-10 14:22',
    lastCommitHash: '5fb3e91',
    lastCommitMessage: 'feat: add CIS Level 2 checks for RHEL 9',
    lastCommitAuthor: 'priya.patel',
    lastCommitTimestamp: '2026-03-16 07:00',
    resources: [
      { type: 'playbook', count: 3 },
      { type: 'role', count: 1 },
      { type: 'collection-dep', count: 2 },
      { type: 'execution-environment', count: 1 },
    ],
    hasProject: true,
  },
];
